# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coincat/coincat_hub.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'coincat/coincat_hub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from dictum_proto.coincat import exchange_pb2 as coincat_dot_exchange__pb2
from dictum_proto.coincat import currency_pb2 as coincat_dot_currency__pb2
from dictum_proto.coincat import order_pb2 as coincat_dot_order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63oincat/coincat_hub.proto\x12\x07\x63oincat\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x16\x63oincat/exchange.proto\x1a\x16\x63oincat/currency.proto\x1a\x13\x63oincat/order.proto\"^\n\x16ListCurrenciesResponse\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12-\n\ncurrencies\x18\x02 \x03(\x0b\x32\x19.coincat.CurrencyResponse\"\\\n\x15ListExchangesResponse\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12,\n\texchanges\x18\x02 \x03(\x0b\x32\x19.coincat.ExchangeResponse\"C\n\x15GetOrderStatusRequest\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ss_code\x18\x02 \x01(\t\"/\n\x16RescheduleOrderRequest\x12\x15\n\rresource_name\x18\x01 \x01(\t2\x96\x04\n\nCoincatHub\x12^\n\rListExchanges\x12\x16.google.protobuf.Empty\x1a\x1e.coincat.ListExchangesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/exchanges\x12\x61\n\x0eListCurrencies\x12\x16.google.protobuf.Empty\x1a\x1f.coincat.ListCurrenciesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/currencies\x12n\n\x0eGetOrderStatus\x12\x1e.coincat.GetOrderStatusRequest\x1a\x16.coincat.OrderResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/{resource_name=orders/*}\x12{\n\x0fRescheduleOrder\x12\x1f.coincat.RescheduleOrderRequest\x1a\x16.coincat.OrderResponse\"/\x82\xd3\xe4\x93\x02)\"\'/v1/{resource_name=orders/*}/reschedule\x12X\n\x13\x43reateExchangeOrder\x12\x15.coincat.OrderRequest\x1a\x16.coincat.OrderResponse\"\x12\x82\xd3\xe4\x93\x02\x0c\"\n/v1/ordersB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coincat.coincat_hub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_COINCATHUB'].methods_by_name['ListExchanges']._loaded_options = None
  _globals['_COINCATHUB'].methods_by_name['ListExchanges']._serialized_options = b'\202\323\344\223\002\017\022\r/v1/exchanges'
  _globals['_COINCATHUB'].methods_by_name['ListCurrencies']._loaded_options = None
  _globals['_COINCATHUB'].methods_by_name['ListCurrencies']._serialized_options = b'\202\323\344\223\002\020\022\016/v1/currencies'
  _globals['_COINCATHUB'].methods_by_name['GetOrderStatus']._loaded_options = None
  _globals['_COINCATHUB'].methods_by_name['GetOrderStatus']._serialized_options = b'\202\323\344\223\002\036\022\034/v1/{resource_name=orders/*}'
  _globals['_COINCATHUB'].methods_by_name['RescheduleOrder']._loaded_options = None
  _globals['_COINCATHUB'].methods_by_name['RescheduleOrder']._serialized_options = b'\202\323\344\223\002)\"\'/v1/{resource_name=orders/*}/reschedule'
  _globals['_COINCATHUB'].methods_by_name['CreateExchangeOrder']._loaded_options = None
  _globals['_COINCATHUB'].methods_by_name['CreateExchangeOrder']._serialized_options = b'\202\323\344\223\002\014\"\n/v1/orders'
  _globals['_LISTCURRENCIESRESPONSE']._serialized_start=166
  _globals['_LISTCURRENCIESRESPONSE']._serialized_end=260
  _globals['_LISTEXCHANGESRESPONSE']._serialized_start=262
  _globals['_LISTEXCHANGESRESPONSE']._serialized_end=354
  _globals['_GETORDERSTATUSREQUEST']._serialized_start=356
  _globals['_GETORDERSTATUSREQUEST']._serialized_end=423
  _globals['_RESCHEDULEORDERREQUEST']._serialized_start=425
  _globals['_RESCHEDULEORDERREQUEST']._serialized_end=472
  _globals['_COINCATHUB']._serialized_start=475
  _globals['_COINCATHUB']._serialized_end=1009
# @@protoc_insertion_point(module_scope)
