# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coincat/currency.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'coincat/currency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63oincat/currency.proto\x12\x07\x63oincat\"5\n\x17\x46ieldValidationResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04rule\x18\x02 \x01(\t\"\x9a\x01\n\rFieldResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08required\x18\x02 \x01(\x08\x12\x12\n\nmin_length\x18\x03 \x01(\x05\x12\x12\n\nmax_length\x18\x04 \x01(\x05\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\x33\n\tvalidates\x18\x06 \x03(\x0b\x32 .coincat.FieldValidationResponse\"\xcc\x02\n\x10\x43urrencyResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07network\x18\x02 \x01(\x05\x12\x17\n\x0ftx_url_template\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x12\n\nshort_name\x18\x05 \x01(\t\x12\x18\n\x10\x61lias_short_name\x18\x06 \x01(\t\x12\x1b\n\x13\x63urrency_short_name\x18\x07 \x01(\t\x12\x10\n\x08\x64\x65\x63imals\x18\x08 \x01(\x05\x12\x16\n\x0eorder_by_index\x18\t \x01(\x01\x12+\n\x0b\x66ields_from\x18\n \x03(\x0b\x32\x16.coincat.FieldResponse\x12)\n\tfields_to\x18\x0b \x03(\x0b\x32\x16.coincat.FieldResponse\x12\x19\n\x11\x61lias_short_names\x18\x0c \x03(\t\x12\x0c\n\x04type\x18\r \x01(\tB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coincat.currency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_FIELDVALIDATIONRESPONSE']._serialized_start=35
  _globals['_FIELDVALIDATIONRESPONSE']._serialized_end=88
  _globals['_FIELDRESPONSE']._serialized_start=91
  _globals['_FIELDRESPONSE']._serialized_end=245
  _globals['_CURRENCYRESPONSE']._serialized_start=248
  _globals['_CURRENCYRESPONSE']._serialized_end=580
# @@protoc_insertion_point(module_scope)
