# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coincat/exchange.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'coincat/exchange.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63oincat/exchange.proto\x12\x07\x63oincat\"\xb5\x01\n\x10\x45xchangeResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x66rom_id\x18\x02 \x01(\t\x12\r\n\x05to_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x04 \x01(\x08\x12-\n\x06levels\x18\x05 \x03(\x0b\x32\x1d.coincat.LevelDetailsResponse\x12\x36\n\ncumulative\x18\x06 \x01(\x0b\x32\".coincat.CumulativeDetailsResponse\"\xdf\x01\n\x14LevelDetailsResponse\x12\x12\n\nmin_amount\x18\x01 \x01(\x01\x12\x12\n\nmax_amount\x18\x02 \x01(\x01\x12\x0f\n\x07reserve\x18\x03 \x01(\x01\x12\x0c\n\x04rate\x18\x04 \x01(\x01\x12\x13\n\x0b\x66\x65\x65_deposit\x18\x05 \x01(\x01\x12\x16\n\x0e\x66\x65\x65_withdrawal\x18\x06 \x01(\x01\x12\x0b\n\x03\x66\x65\x65\x18\x07 \x01(\x01\x12\"\n\x1arate_effective_lower_limit\x18\x08 \x01(\x01\x12\"\n\x1arate_effective_upper_limit\x18\t \x01(\x01\"\xe4\x01\n\x19\x43umulativeDetailsResponse\x12\x12\n\nmin_amount\x18\x01 \x01(\x01\x12\x12\n\nmax_amount\x18\x02 \x01(\x01\x12\x0f\n\x07reserve\x18\x03 \x01(\x01\x12\x0c\n\x04rate\x18\x04 \x01(\x01\x12\x13\n\x0b\x66\x65\x65_deposit\x18\x05 \x01(\x01\x12\x16\n\x0e\x66\x65\x65_withdrawal\x18\x06 \x01(\x01\x12\x0b\n\x03\x66\x65\x65\x18\x07 \x01(\x01\x12\"\n\x1arate_effective_lower_limit\x18\x08 \x01(\x01\x12\"\n\x1arate_effective_upper_limit\x18\t \x01(\x01\x42&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coincat.exchange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_EXCHANGERESPONSE']._serialized_start=36
  _globals['_EXCHANGERESPONSE']._serialized_end=217
  _globals['_LEVELDETAILSRESPONSE']._serialized_start=220
  _globals['_LEVELDETAILSRESPONSE']._serialized_end=443
  _globals['_CUMULATIVEDETAILSRESPONSE']._serialized_start=446
  _globals['_CUMULATIVEDETAILSRESPONSE']._serialized_end=674
# @@protoc_insertion_point(module_scope)
