# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/accrual_type.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/accrual_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/accrual_type.proto*\x84\x01\n\x0b\x41\x63\x63rualType\x12\x18\n\x14\x41\x43\x43RUAL_TYPE_UNKNOWN\x10\x00\x12\x18\n\x14\x41\x43\x43RUAL_TYPE_INVOICE\x10\x01\x12\x1b\n\x17\x41\x43\x43RUAL_TYPE_CORRECTION\x10\x02\x12$\n ACCRUAL_TYPE_TEMPORAL_CORRECTION\x10\x03\x42&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.accrual_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_ACCRUALTYPE']._serialized_start=29
  _globals['_ACCRUALTYPE']._serialized_end=161
# @@protoc_insertion_point(module_scope)
